- name: add apt key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc

- name: add apt repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian testing main"
    update_cache: yes

- name: install rabbitmq
  apt:
    pkg: rabbitmq-server
    state: present

- name: enable management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: install rabbitmqadmin
  get_url:
    url: http://localhost:15672/cli/rabbitmqadmin
    dest: /usr/local/bin/rabbitmqadmin
    mode: 0755
