- include: install.yml
  tags:
    - rabbitmq
    - rabbitmq-install

- name: configure rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq
  tags:
    - rabbitmq
    - rabbitmq-configure

- name: set erlang cookie
  copy:
    content: "{{ rabbitmq_cookie }}"
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  when: rabbitmq_clustered
  register: cookie_result
  notify:
    - restart rabbitmq
  tags:
    - rabbitmq
    - rabbitmq-configure

- include: reset_rabbitmq.yml
  when: cookie_result|changed
  tags:
    - rabbitmq
    - rabbitmq-configure

- meta: flush_handlers

- name: wait for rabbitmq to start
  wait_for:
    port: 5672
  tags:
    - rabbitmq
    - rabbitmq-configure

- name: ensure ha mode on all queues
  rabbitmq_policy:
    name: ha
    pattern: .*
    tags:
      ha-mode: all
  when: rabbitmq_clustered
  tags:
    - rabbitmq
    - rabbitmq-configure
