- include: install.yml
  tags:
    - install

- name: configure rabbitmq
  copy:
    src: rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq
  tags:
    - configure

- meta: flush_handlers
