- name: add apt key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc

- name: add apt repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian testing main"
    update_cache: yes

- name: install rabbitmq
  apt:
    pkg: rabbitmq-server
    state: present

- name: configure rabbitmq
  copy:
    src: rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq

- name: enable management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- meta: flush_handlers
