# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "node1" do |box|
    box.vm.hostname = "node1"
    box.vm.network "private_network", ip: "10.0.77.101"
  end

  config.vm.define "node2" do |box|
    box.vm.hostname = "node2"
    box.vm.network "private_network", ip: "10.0.77.102"
  end

  config.vm.define "node3" do |box|
    box.vm.hostname = "node3"
    box.vm.network "private_network", ip: "10.0.77.103"

    config.vm.provision "ansible" do |a|
      a.playbook = "playbook.yml"
      a.sudo = true

      a.limit = "all"

      a.groups = {
        "rabbitmq" => ["node1", "node2", "node3"],
      }
    end
  end
end
